version: '2.2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    container_name: elasticsearch
    environment:
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TAKE_FILE_OWNERSHIP=1"
      - cluster.name=docker-cluster
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - discovery.seed_hosts=elasticsearch2:9300,elasticsearch3:9300
    volumes:
      - ./var/es-cluster/esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    container_name: elasticsearch2
    environment:
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TAKE_FILE_OWNERSHIP=1"
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - node.name=elasticsearch2
      - discovery.seed_hosts=elasticsearch:9300,elasticsearch3:9300
    volumes:
      - ./var/es-cluster/esdata2:/usr/share/elasticsearch/data

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    container_name: elasticsearch3
    environment:
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TAKE_FILE_OWNERSHIP=1"
      - cluster.name=docker-cluster
      - node.name=elasticsearch3
      - cluster.initial_master_nodes=elasticsearch
      - discovery.seed_hosts=elasticsearch:9300,elasticsearch2:9300
    volumes:
      - ./var/es-cluster/esdata3:/usr/share/elasticsearch/data

  headPlugin:
    image: 'mobz/elasticsearch-head:5'
    container_name: head
    ports:
      - '9100:9100'
